In [1]:
import requests
from bs4 import BeautifulSoup

import pandas as pd
import time

# Functions
def convert_df(area_lista, endereco_lista, valor_lista, quarto_lista, banheiro_lista, vaga_lista):
    data = {'area': area_lista,
            'endereco':endereco_lista,
            'aluguel': valor_lista,
            'quartos': quarto_lista,
            'banheiros': banheiro_lista,
            'vagas': vaga_lista}
    df = pd.DataFrame(data)

    return df

def scrap(url):
    c=requests.get(url).content
    soup=BeautifulSoup(c)

    area_tags = soup.find_all('span', {'class':'property-card__detail-value js-property-card-value property-card__detail-area js-property-card-detail-area'})   
    area_lista=[ar.text for ar in area_tags]
        
    address_tags = soup.find_all('span', {'class':'property-card__address'})
    endereco_lista=[en.text for en in address_tags]

    price_tags = soup.find_all('div', {'class':'property-card__price js-property-card-prices js-property-card__price-small'})
    valor_lista = [vl.text for vl in price_tags]    
   
    room_tags = soup.find_all('li', {'class':'property-card__detail-item property-card__detail-room js-property-detail-rooms'})   
    quarto_lista=[qt.text for qt in room_tags]
    
    bath_tags = soup.find_all('li', {'class':'property-card__detail-item property-card__detail-bathroom js-property-detail-bathroom'})  
    banheiro_lista=[ba.text for ba in bath_tags]

    garage_tags = soup.find_all('li', {'class':'property-card__detail-item property-card__detail-garage js-property-detail-garages'})  
    vaga_lista=[vg.text for vg in garage_tags]
    
    df=convert_df(area_lista, endereco_lista, valor_lista, quarto_lista, banheiro_lista, vaga_lista)

    return df

In [2]:
qtpaginas = 3
URL = 'https://www.vivareal.com.br/aluguel/sp/sao-caetano-do-sul/'

paginas = ['']
for i in range(2,qtpaginas):
    a = '?pagina-'+str(i)
    paginas.append(a)

df_lista = []
for pg in paginas:
    #url=URL.format(pg)
    url = URL+pg
    print('Coletando URL:', url)
    try:
        df=scrap(url)
    except Exception as e:
        print('Erro ao coletar URL:', url)
        print(e)
    df_lista.append(df)
    time.sleep(1)
df_final = pd.concat(df_lista)

Coletando URL: https://www.vivareal.com.br/aluguel/sp/sao-caetano-do-sul/
Coletando URL: https://www.vivareal.com.br/aluguel/sp/sao-caetano-do-sul/?pagina-2

In [3]:
df_final.head(36)

,area,endereco,aluguel,quartos,banheiros,vagas
0,37,"Alameda Terracota - Cerâmica, São Caetano do S...",R$ 1.500 /Mês,-- Quarto,1 Banheiro,1 Vaga
1,175,"Santa Maria, São Caetano do Sul - SP",R$ 3.000 /Mês R$ 740.000,3 Quartos,1 Banheiro,-- Vaga
2,90,"Rua Solimões, 263 - Santa Maria, São Caetano d...",R$ 1.600 /Mês,3 Quartos,1 Banheiro,2 Vagas
3,3400,"Rua Perrella, 304 - Fundação, São Caetano do S...",R$ 35.000 /Mês,-- Quarto,8 Banheiros,-- Vaga
4,125,"Alameda São Caetano, 1582 - Santa Paula, São C...",R$ 3.300 /Mês,-- Quarto,1 Banheiro,-- Vaga
5,180,"Santa Paula, São Caetano do Sul - SP",R$ 2.400 /Mês R$ 580.000,2 Quartos,2 Banheiros,1 Vaga
6,55,"Cerâmica, São Caetano do Sul - SP",R$ 2.909 /Mês,-- Quarto,1 Banheiro,1 Vaga
7,293,"Prosperidade, São Caetano do Sul - SP",R$ 6.000 /Mês,-- Quarto,2 Banheiros,-- Vaga
8,34,"Rua Alegre, 470 - Santa Paula, São Caetano do ...",R$ 1.300 /Mês,-- Quarto,1 Banheiro,1 Vaga
9,80,"Avenida Goiás - Santo Antônio, São Caetano do ...",R$ 1.500 /Mês,-- Quarto,1 Banheiro,-- Vaga
10,120,Avenida Doutor Augusto de Toledo - Santa Paula...,R$ 2.100 /Mês,3 Quartos,3 Banheiros,1 Vaga
11,606,"Avenida Conde Francisco Matarazzo - Fundação, ...",R$ 20.000 /Mês,-- Quarto,3 Banheiros,-- Vaga
12,70,"Avenida Senador Roberto Simonsen - Centro, São...",R$ 1.600 /Mês,2 Quartos,2 Banheiros,1 Vaga
13,1879,"Avenida Conde Francisco Matarazzo - Fundação, ...",R$ 55.000 /Mês,-- Quarto,4 Banheiros,-- Vaga
14,68,"Rua Luís Louza, 221 - Olímpico, São Caetano do...",R$ 2.700 /Mês,2 Quartos,2 Banheiros,1 Vaga
15,100,"Avenida Tijucussu - Olímpico, São Caetano do S...",R$ 1.800 /Mês,2 Quartos,2 Banheiros,-- Vaga
16,250,"Rua Manoel Augusto Ferreirinha, 736 - Nova Ger...",R$ 5.200 /Mês,-- Quarto,2 Banheiros,-- Vaga
17,1360,"Barcelona, São Caetano do Sul - SP",R$ 25.000 /Mês,-- Quarto,4 Banheiros,10 Vagas
18,41,"Rua Pará, 139 - Centro, São Caetano do Sul - SP",R$ 1.600 /Mês,-- Quarto,2 Banheiros,1 Vaga
19,61,"Rua Rui Barbosa - Santo Antônio, São Caetano d...",R$ 1.700 /Mês,2 Quartos,1 Banheiro,2 Vagas
20,127,"Rua Nilo Peçanha - Santa Paula, São Caetano do...",R$ 2.800 /Mês,3 Quartos,2 Banheiros,2 Vagas
21,109,"Santa Maria, São Caetano do Sul - SP",R$ 2.000 /Mês R$ 500.000,3 Quartos,3 Banheiros,1 Vaga
22,110,"Santa Paula, São Caetano do Sul - SP",R$ 2.700 /Mês,4 Quartos,2 Banheiros,-- Vaga
23,320,"Fundação, São Caetano do Sul - SP",R$ 5.800 /Mês,-- Quarto,2 Banheiros,-- Vaga
24,55,"Cerâmica, São Caetano do Sul - SP",R$ 1.500 /Mês,-- Quarto,1 Banheiro,2 Vagas
25,60,"Rua Alegre - Santa Paula, São Caetano do Sul - SP",R$ 1.800 /Mês,2 Quartos,2 Banheiros,2 Vagas
26,86,"Boa Vista, São Caetano do Sul - SP",R$ 2.200 /Mês,2 Quartos,2 Banheiros,-- Vaga
27,1020,"Rua Major Carlos Del Prete, 700 - Centro, São ...",R$ 8.000 /Mês R$ 3.400.000,-- Quarto,2 Banheiros,15 Vagas
28,80,"Barcelona, São Caetano do Sul - SP",R$ 2.000 /Mês,2 Quartos,1 Banheiro,1 Vaga
29,20,"Rua Alegre, , 400 - Santa Paula, São Caetano d...",R$ 1.050 /Mês,1 Quarto,1 Banheiro,1 Vaga
30,53,"Avenida Presidente Kennedy, 3500 - Santa Paula...",R$ 1.500 /Mês R$ 300.000,-- Quarto,1 Banheiro,1 Vaga
31,37,"Rua Alegre, , 400 - Santa Paula, São Caetano d...",R$ 1.300 /Mês,1 Quarto,1 Banheiro,1 Vaga
32,300,"Avenida Senador Roberto Simonsen, 1318 - Cerâm...",R$ 4.300 /Mês,-- Quarto,2 Banheiros,-- Vaga
33,158,"Rua Rafael Corrêa Sampaio - Santo Antônio, São...",R$ 2.300 /Mês,3 Quartos,6 Banheiros,2 Vagas
34,108,"Rua Amazonas, 521 - Centro, São Caetano do Sul...",R$ 3.000 /Mês,-- Quarto,2 Banheiros,2 Vagas
35,60,"Santa Maria, São Caetano do Sul - SP",R$ 1.200 /Mês,2 Quartos,1 Banheiro,1 Vaga